spring.application.name=project-manager

spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

member-api.base-url=http://localhost:8080

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha

spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=true

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

server.port=8080

resilience4j.circuitbreaker.instances.member-api.failure-rate-threshold=60
resilience4j.circuitbreaker.instances.member-api.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.member-api.sliding-window-size=10
resilience4j.circuitbreaker.instances.member-api.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.member-api.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.member-api.record-exceptions[0]=java.lang.Exception

resilience4j.retry.instances.member-api.max-attempts=3
resilience4j.retry.instances.member-api.wait-duration=500ms

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true